### ISSUE TITLE
Others components within 'md-data-table-cell' no longer work.

### ISSUE THREAD

**Issue by emanuelvictor** [iamisti/md-data-table#18]
Previously it was possible to use a md-button inside the <md-data-table-cell>. But this is no longer possible, since the transclude does not meet this requirement.

Follow the code in md-data-table.js:

   transclude(function (clone) {
       //TODO: better idea?
       var cellValue = $parse(clone.html().replace('{{', '').replace('}}', ''))($scope);
       mdDataTableRowCtrl.addToRowDataStorage(cellValue);
   });

**Comment by iamisti** [comment]
Fixed, pls try it out.
Readme document updated as well with the details.

You have to add an `html-content="true"` attribute for the column that has html content instead of a simple value.
