### ISSUE TITLE
Project init

### ISSUE THREAD

**Issue by lellex** [iamisti/md-data-table#23]
Hi,

I forked the project but can't achieve to lauch gulp correctly. Seems to have a problem with bower's path directory or something like this...
I ran npm install && bower install. Is there anything else I forgot ?

**Comment by iamisti** [comment]
Can u pls copy  the error message? It should be okay with the following commands:
`npm install`
`bower install`
`gulp`

**Comment by iamisti** [comment]
@lellex Is that solved your issue?

**Comment by iamisti** [comment]
Do you still have this problem?

2015-07-10 9:28 GMT+02:00 Alexandra J <notifications@github.com>:
