### ISSUE TITLE
Unable to resolve in Bower

### ISSUE THREAD

**Issue by TomSchober** [iamisti/md-data-table#27]
bower.json

{
  "name": "myProject",
  "description": "My Project",
  "version": "0.0.1",
  "homepage": "...",
  "license": "MIT",
  "private": true,
  "dependencies": {
    "angular": "^1.4.x",
    "angular-animate": "^1.4.x",
    "angular-aria": "^1.4.x",
    "angular-material": "^0.9.x",
    "material-design-icons": "2.0.x",
    "angular-ui-router": "^0.2.15",
    "md-data-table": "0.0.0"
  }
}

$ bower install
bower md-data-table#0.0.0   not-cached git://github.com/iamisti/md-data-table.git#0.0.0
bower md-data-table#0.0.0      resolve git://github.com/iamisti/md-data-table.git#0.0.0
bower md-data-table#0.0.0 ENORESTARGET No tag found that was able to satisfy 0.0.0

Additional error details:
No versions found in git://github.com/iamisti/md-data-table.git

**Comment by iamisti** [comment]
Try to not specify the version number. Currently I don't have any official releases. What happens if you just use 'latest' instead of the '0.0.0'?

**Comment by TomSchober** [comment]
There you go.  I was being too specific.  I'll wait for the official releases on bower and npm.

**Comment by iamisti** [comment]
Yeah I'm planning to soon. Within 1-2 weeks I'll do a release for you guys.

**Comment by iamisti** [comment]
@TomSchober released v0.1 some day before.
