### ISSUE TITLE
Multiple directives asking for transclusion

### ISSUE THREAD

**Issue by syedsuhail** [iamisti/md-data-table#30]
I am getting the following error when trying to use md-data-table in my project.

`Error: [$compile:multidir] Multiple directives [mdButton, mdButton (module: material.components.button)] asking for transclusion`

Is this because of mdButton directives in both ngMaterial and md-data table?  How can I fix this?

**Comment by iamisti** [comment]
Can u please provide me a plunkr example?

**Comment by iamisti** [comment]
Cant reproduce.
