### ISSUE TITLE
sort-value property to allow sorting when used HTML or filtered value

### ISSUE THREAD

**Issue by Nekmo** [iamisti/md-data-table#31]
In my case the value of the cell does not allow proper sorting:

    <md-data-table-cell>
         {{ node.size | bytes }}
    </md-data-table-cell>

This may return eg "9MiB" and "1GiB".  I need to sort in bytes. This is my proposal.

    <md-data-table-cell sort-value="node.size">
          {{ node.size | bytes }}
    </md-data-table-cell>

**Comment by jeffzmartin** [comment]
The sort-by attribute has been added to the md-data-table-column directive to support this type of capability.

**Comment by iamisti** [comment]
Exactly. Functionality has been added with this change
https://github.com/iamisti/md-data-table/pull/36
