### ISSUE TITLE
[BUG] Error when used ngClass in mdDataTableRow

### ISSUE THREAD

**Issue by Nekmo** [iamisti/md-data-table#32]
Example:

                    <md-data-table-row ng-repeat="node in nodes | orderBy:['type', 'name']"
                                       ng-class="{'ani-slide': nodes != null}">

Error is:

    Error: [$parse:syntax] Syntax Error: Token '{' is an unexpected token at column 19 of the expression [{anislide: nodes} {'selectedRow': getRowOptions().selected}] starting at [{'selectedRow': getRowOptions().selected}].
    http://errors.angularjs.org/1.4.4/$parse/syntax?p0=%7B&p1=is%20an%20unexpected%20token&p2=19&p3=%7Banislide%3A%20nodes%7D%20%7B'selectedRow'%3A%20getRowOptions().selected%7D&p4=%7B'selectedRow'%3A%20getRowOptions().sele

**Comment by iamisti** [comment]
can u pls provide a live example in plunker or on any similar page to see the issue?

**Comment by iamisti** [comment]
You can't add additional classes to rows atm. Closing the ticket.
If u need a feature to support adding classes,  please raise it.
