### ISSUE TITLE
Cannot use md-data-table in strict mode

### ISSUE THREAD

**Issue by Keepertje** [iamisti/md-data-table#33]
Hi! I tried using the table. Our application uses the javascript 'strict mode' but because of that I get the following errors:

Error: [$injector:strictdi] mdDataTableDirective is not using explicit annotation and cannot be invoked in strict mode (...)
angular.js:12416 Error: [$injector:strictdi] mdDataTableHeaderRowDirective is not using explicit annotation and cannot be invoked in strict mode (...)
angular.js:12416 Error: [$injector:strictdi] mdDataTableColumnDirective is not using explicit annotation and cannot be invoked in strict mode (...)
angular.js:12416 Error: [$injector:strictdi] mdDataTableRowDirective is not using explicit annotation and cannot be invoked in strict mode (...)
angular.js:12416 Error: [$injector:strictdi] mdDataTableCellDirective is not using explicit annotation and cannot be invoked in strict mode (...)

**Comment by rabih-elzahr** [comment]
Same here...any solution?

**Comment by iamisti** [comment]
@Keepertje, @rabih-elzahr I've pushed my changes and now it should work.
Can u please one of you verify that my fix is solving your issue?

**Comment by Keepertje** [comment]
@iamisti  It seems to work now :), thank you !
