### ISSUE TITLE
Does md-data-table work with the versions below?

### ISSUE THREAD

**Issue by iamryandrake** [iamisti/md-data-table#38]
Having issues with my karma tests and I'm trying to resolve and think it's a versioning issue.

Are you able to confirm if they work with the following?
Angular 1.4.7
Angular-Material 0.11.1

Thanks!

**Comment by iamisti** [comment]
Just checked, everything works fine with the new versions.
I've also updated the packages.

**Comment by AcCREW** [comment]
Still showing "ECONFLICT Unable to find suitable version for angular" when im trying to install it with bower on angular version "angular": "^1.4.7"?

**Comment by iamisti** [comment]
Can you provide me an example/copy of your bower file?
Thanks!

**Comment by AcCREW** [comment]
{
  "name": "Blabla",
  "description": "Blabla",
  "dependencies": {
    "angular": "^1.4.7",
    "bootstrap": "~3.3.5",
    "jquery": "~2.1.4",
    "font-awesome": "~4.4.0",
    "angular-bootstrap": "~0.13.4",
    "metisMenu": "~2.2.0",
    "v-button": "~1.1.1",
    "angular-strap": "~2.3.3",
    "angular-motion": "~0.4.3",
    "angular-animate": "~1.4.7",
    "bootstrap-additions": "~0.3.1",
    "angular-material": "~0.11.2",
    "angular-messages": "~1.4.7",
    "angular-material-data-table": "~0.8.14"
  }
}

This is it :)

**Comment by iamisti** [comment]
@AcCREW still having your problem with v0.1 too?

**Comment by iamisti** [comment]
Closing it down until @AcCREW has different experience.
