### ISSUE TITLE
Sort direction doesn't reset when clicking a different column

### ISSUE THREAD

**Issue by gjr-qm** [iamisti/md-data-table#39]
Hi,

Great datatable! I like it when the Google guidelines are used as much as possible.

The issue is that when you have a column sorted descending and you click another column, the sort direction for the new column still is descending, but the arrow is pointing in the ascending direction. I when you click another column, the initial direction should always be ascending.

Want me to make a pull request to fix it?

**Comment by iamisti** [comment]
You right, but it's only happening on the first click on the table. After it, every column sorting is working for the first try.
Sure, please go ahead and try to fix it encapsulating with a pull request.

Thanks! :+1:
