### ISSUE TITLE
Header/sorting ideas

### ISSUE THREAD

**Issue by gjr-qm** [iamisti/md-data-table#40]
Just some ideas that will make the table a little more attractive:
- animating the sort icon when changing sort direction
- put a ripple effect when clicking a sortable header (it's an element with button behaviour)

I can implement it if you want,

**Comment by iamisti** [comment]
The idea is great, but still it should be only additional features that you can switch on anytime if you need it. Due it'll imply some performance degradations as well. E.g.: should be disabled at default.

Big welcome for contributing to the project. So feel free to implement and make it optional to use please :+1:

**Comment by gjr-qm** [comment]
Ok, i agree with you that extra functionality should be optional, especially when it has performance penalties. But making everything an option will make everything more complex (including the documentation).

You are already using the ripple effect on the checkboxes and the change will only consist of one extra attribute on the th-tag in the header template.

The change for the animation needs some rework of the template and some css. I could implement this change in a way that animation is off by default, but can be turned on by putting a class on the md-data-table-column. Togeter with this change i could fix the problem that de sort arrows don't rotate in FireFox (vendor prefixes are missing).

What if i just make a pull request, so you can decide wether the changes are worth the merge?

**Comment by iamisti** [comment]
@gjr-qm It's basically done. I'll make it configurable in the future, but the ripple effect and the sorting animation is in place. Thank you for your contribution!
