### ISSUE TITLE
pagination support

### ISSUE THREAD

**Issue by rudzikdawid** [iamisti/md-data-table#44]
Do you have plan to implement a pagination feature ?

**Comment by iamisti** [comment]
I'd not call it pagination. I have plans for vertical scrolling which solves the problem with bigger amount of data.
Howerver I didn't think about the scenario when you fetching your data from a backend and obviously you do need some kind of paging there. I'm still thinking about the solution. My only problem is that google material design doesn't have the concept of pagination.

**Comment by rudzikdawid** [comment]
![Image of pagination](https://camo.githubusercontent.com/ca27ba0b376600b0e01050bd9fdbad644a60189a/687474703a2f2f6d6174657269616c2d64657369676e2e73746f726167652e676f6f676c65617069732e636f6d2f7075626c6973682f6d6174657269616c5f765f342f6d6174657269616c5f6578745f7075626c6973682f3042336d4f506f4a6c78694668555445776132314a5545747a61306b2f636f6d706f6e656e74735f646174617461626c65735f63617264735f7461626c65636172642e706e67)

Rows per page (on the bottom) - in my opinion this is kind of pagination feature

**Comment by iamisti** [comment]
Hmm somehow I missed that part. Okay than we'll definitely implement this one.
This can have more priority in my list, since it's a common used feature.
Thank you for your comment!

**Comment by gjr-qm** [comment]
Some time ago i was busy with this feature, but until now didn't have the time to finish it. I already made some changes that could be usefull i think. I implemented the template in the footer and the options for the pagination. I was about to implement the pagination functionality (maybe using https://github.com/michaelbromley/angularUtils/tree/master/src/directives/pagination is a good idea?).

I'm glad to help out if someone needs help with this.

**Comment by iamisti** [comment]
@rudzikdawid , @gjr-qm 
Pagination support implemented, see v0.2 release.

**Comment by gjr-qm** [comment]
:+1: Nice work!

**Comment by rudzikdawid** [comment]
great work :)

**Comment by iamisti** [comment]
Thanks guys! :bowtie:

**Comment by pavantummalapalli** [comment]
pagination with html support throwing infdig error . 
http://codepen.io/pavantummalapalli/pen/wGddaj?editors=1111
