### ISSUE TITLE
usage

### ISSUE THREAD

**Issue by johnnylima** [iamisti/md-data-table#45]
Olá,

Meu nome é Johnny e gostaria de usar o md-data-table no meu projeto de estudo. Fiz a instalação através do "bower install". Porém não consigo implementar. Pode meu ajudar?

Grato!

**Comment by iamisti** [comment]
I'm sorry but I only speak in english. Can you please write me in english?

2015-12-21 16:40 GMT+01:00 johnnylima <notifications@github.com>:

**Comment by iamisti** [comment]
@johnnylima If you have problems with installing, please follow the instructions on the home page.
`bower install md-data-table` should do the trick, or if you have it as a bower dependency, then try to do like this: `"md-data-table": "v0.2.1"`

Closing the issue until u don't give a different response.
