### ISSUE TITLE
html-content affects column sorting

### ISSUE THREAD

**Issue by davidcui2** [iamisti/md-data-table#48]
Thanks for the effort updating this great feature. I came up with the issue using a basic structure (slightly simplified version):

    <md-data-table selectable-rows="true" sortable-columns="true" animate-sort-icon="true">
        <md-data-table-header-row>
            <md-data-table-column sortable-rows-default> {{lo.Type}} </md-data-table-column>
            <md-data-table-column align-rule="left"> {{lo.Name}} </md-data-table-column>
        </md-data-table-header-row>

        <md-data-table-row ng-repeat="item in si.items">
            <md-data-table-cell html-content="true">
                
                {{item.ItemType)}}
            </md-data-table-cell>
            <md-data-table-cell>{{item.Name}}</md-data-table-cell>
        </md-data-table-row>
    </md-data-table>

And I did some further experiments. After added the `html-content="true"` to any of the `md-data-table-cell`, it will prevent sorting from re-rendering the whole column, even when I clicked the header of the same column. However, all other rows are still being correctly sorted.

I'm doing so because I want to insert different `md-icon`s (basically different names of the icon) into the cells, there might be other better approaches. Please suggest if you know any :)

BTW, I'm still using v1.0 as I had some errores when using later versions. I didn't have the time to test whether the error came from some conflicts as I'm also using Angular-material.

> TypeError: Cannot read property 'hasOwnProperty' of undefined
        at new mdtPaginationHelper (md-data-table.js:200)
        ...

**Comment by iamisti** [comment]
@davidcui2 Thank you for your remarks. I'll fix that as soon as I can. Basically I'm working on the issue now.

**Comment by iamisti** [comment]
Fixed with v0.2.4
Please verify it! 

Thanks!
