### ISSUE TITLE
Specify data via HTML

### ISSUE THREAD

**Issue by dbkaplun** [iamisti/md-data-table#5]
I'd be glad to detail my use case if you're interested!

**Comment by iamisti** [comment]
Can u please explain a bit more? Just because data is already specified via html and I don't see what you want to do achieve. Thanks.

**Comment by dbkaplun** [comment]
I just meant that it would be better if [this code](https://github.com/iamisti/md-data-table/blob/2946195094df90dcf612f0435d67ead796b39e0f/demo/example.js#L10-L17) was replaced with something like:

```
<md-data-table-row>
  <md-data-table-cell>Frozen joghurt</md-data-table-cell>
  <md-data-table-cell>159</md-data-table-cell>
  <md-data-table-cell>6.0</md-data-table-cell>
  ...
</md-data-table-row>
<md-data-table-row>
  <md-data-table-cell>Ice cream sandwitch</md-data-table-cell>
  <md-data-table-cell>237</md-data-table-cell>
  <md-data-table-cell>9.0</md-data-table-cell>
  ...
</md-data-table-row>
...
```

That would be more powerful and easy to use.

**Comment by iamisti** [comment]
It's sounds interesting.
Would you like to have fill the table with data only in this way, or you would like to preserve the one that we have now (providing an array)?

**Comment by iamisti** [comment]
But I agree, let's do this :)

**Comment by aoakeson** [comment]
I am still not seeing this functional.  Html content in the cells does not render.  I noticed your comment where it says something to figure out something for including html content, but this issue is closed.  What is the status of it?

**Comment by iamisti** [comment]
You have to add an html-content="true" attribute for the column that has html content instead of a simple value.

**Comment by aoakeson** [comment]
Thank you for this.  Just to clarify, if you want html content on the row, you must put it in the cell instead of the column.  

Example: 
```html
<md-data-table-cell html-content="true">
<span ng-repeat="person in people">{{person.Name}}, </span>
</md-data-table-cell>
```
