### ISSUE TITLE
How do I add buttons per row

### ISSUE THREAD

**Issue by akhopkar** [iamisti/md-data-table#7]
Hi there,

Another question was that I saw your docs and didn't really see in the configuration how I am supposed to configure a column such that it has icon buttons where I can set ng-click attributes to controller methods on my scope.

Is this possible on your table?

Amarish

**Comment by iamisti** [comment]
Hi, the reposiry was created 3 days ago, so it doesnt have the functionalities at the moment.
But what it does is the concept of functionalities.
At some points, it's still not described in detail,  but it will as soon it has been implemented.

**Comment by iamisti** [comment]
Documentation improved. Now u can clearly see what is svailable and what is not.
